packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.1.0
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsdown: ^0.15.6
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.9
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.7.1
  utils:
    tinyexec: ^1.0.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
ignoreWorkspaceRootCheck: true
