packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^6.0.0
    '@antfu/ni': ^27.0.0
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.38.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.5
    simple-git-hooks: ^2.13.1
    taze: ^19.8.1
    tsdown: ^0.15.9
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.11
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.9.1
  utils:
    tinyexec: ^1.0.1

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
