packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    czg: ^1.12.0
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.7
  inlined:
    '@antfu/utils': ^9.2.1
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.5.2
  utils:
    tinyexec: ^1.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
